// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection — Neon's/Supabase's
    // pooled connection (PgBouncer transaction mode) doesn't support the
    // session-level advisory lock `prisma migrate` takes, and times out
    // with P1002. DIRECT_URL falls back to DATABASE_URL so plain (non-pooled)
    // setups, like local Postgres, don't need a second env var.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
